trigger:
  branches:
    include:
      - infra_*
  paths:
    include:
      -  'terraform/*'
      -  'api/*'
steps:
   - checkout: self
     persistCredentials: true
   - script: |
      git config --global user.email 'nitya_shankar@outlook.com'
      git config --global user.name 'nitya'
   - task: NodeTool@0
     inputs:
      versionSpec: '14.x'    
   - task: UsePythonVersion@0
     inputs:
      versionSpec: '3.9' 
   - script: |
      npm install -g commitizen
      cz bump --check-consistency --changelog
      git push --follow-tags origin HEAD:$(Build.SourceBranchName)
     condition: eq(variables['Build.SourceBranch'], 'refs/heads/infra_v1.0')
     displayName: 'Bump package version number'
     
# infra pipleine
   - task: PublishPipelineArtifact@1
     inputs:
       targetPath: '$(System.DefaultWorkingDirectory)/'
       artifact: 'infra'
       publishLocation: 'pipeline'
