trigger:
  branches:
    include:
      - infra_*
  paths:
    include:
      -  '*'
      -  #'api/*'
steps:
   - task: gitversion/setup@0
     inputs:
       versionSpec: '5.x'
   - task: gitversion/execute@0
     inputs:
       useConfigFile: true
       configFilePath: 'GitVersion.yml'
     
# infra pipleine
   - task: PublishPipelineArtifact@1
     inputs:
       targetPath: '$(System.DefaultWorkingDirectory)/'
       artifact: 'infra'
       publishLocation: 'pipeline'
