trigger:
  branches:
    include:
      - infra
  paths:
    include:
      -  '*'
  
# infra pipleine
steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/'
    artifact: 'infra'
    publishLocation: 'pipeline'