[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.commitizen]
version="1.0.0"
version_files = [
    "setup.py:version"
]
bump_message = "release $current_version -> $new_version [skip ci]"