#build node app
trigger:
  branches:
    include:
      - 'infra_*'
  paths:
    include:
      - 'front-end/*'

pool:
  vmImage: ubuntu-latest
  
steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: | 
        cd front-end
        npm install
    - script: set CI=true&&npm test
      displayName: Test
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'