#build node app
trigger:
  branches:
    include:
      - 'infra_*'
  paths:
    include:
      - 'front-end/*'

pool:
  vmImage: ubuntu-latest
  
steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: | 
        cd front-end
        npm install
    #- script: | 
    #    cd front-end
    #    npm run test
    #  displayName: 'npm install,start and test'
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
      displayName: 'S3 Upload: www.dev01.location-tracker.com'
      inputs:
        awsCredentials: 'AWS_credentials'
        regionName: 'eu-west-1'
        bucketName: 'www.dev01.location-tracker.com'
        sourceFolder: 'front-end'
    - task: AmazonWebServices.aws-vsts-tools.AWSCLI.AWSCLI@1
      displayName: 'AWS CLI: cloudfront'
      inputs:
       awsCredentials: 'AWS_credentials'
       regionName: 'eu-west-1'
       awsCommand: cloudfront
       awsSubCommand: 'create-invalidation'
       awsArguments: '--distribution-id EMV7B0J71SL6M --paths /*'
       failOnStandardError: false
