trigger:
  branches:
    include:
      - infra_*
      - master
  paths:
    include:
      -  'api/*'

stages:
 - stage:
   displayName: Run unit tests
   jobs:
    - job: run_unit_tests_job
      displayName: unit tests
      steps:
      
       - task: DotNetCoreCLI@2
         displayName: 'build prject'
         inputs:
          command: 'build'
          projects: '**/LocationTrackerAPI/*.csproj'
         
       - task: DotNetCoreCLI@2
         displayName: run visual studio
         inputs:
             command: test
             projects: '**/LocationTrackerAPI.Tests/*.csproj'
             arguments: '--configuration debug --collect:"XPlat Code Coverage"'
             codeCoverageEnabled: true
        
       - task: PowerShell@2
         displayName: 'Install ReportGenerator Code Coverage  Tool'
         inputs:
            targetType: 'inline'
            script: dotnet tool install --global dotnet-reportgenerator-globaltool

       - task: PowerShell@2
         displayName: 'Execute ReportGenerator Code Coverage Command'
         inputs:
            targetType: 'inline'
            script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
        
       - task: PublishCodeCoverageResults@1
         displayName: 'Public Code Coverage Results'
         inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml' 

#package API artifact
 - stage:
   displayName : publish artifacts
   jobs:
    - job:
      displayName : build job
      steps:
        - task: PublishPipelineArtifact@1
          inputs:
           targetPath: '$(System.DefaultWorkingDirectory)/api'
           artifact: 'api'
           publish Location: 'pipeline'
          
        - task: AmazonWebServices.aws-vsts-tools.LambdaNETCoreDeploy.LambdaNETCoreDeploy@1
          displayName: 'Deploy .NET Core to Lambda: arn:aws:lambda:eu-west-1:007060634107:function:loc_report_lambda_function '
          inputs:
            awsCredentials: 'AWS_credentials'
            regionName: 'eu-west-1'
            lambdaProjectPath: '$(System.DefaultWorkingDirectory)/_api_build_ci/api/api/LocationTrackerAPI'
            functionName: 'arn:aws:lambda:eu-west-1:007060634107:function:loc_report_lambda_function'
            functionHandler: 'LocationTrackerAPI::LocationTrackerAPI.Functions::LocationReport'
            functionMemory: 256
            functionTimeout: 30
