trigger:
  branches:
    include:
      - infra_*
      - master
  paths:
    include:
      -  'api/*'
  variables:
   major: 1
   minor: 1
   name: $(major).$(minor)$(Rev:.r)    
 #package API artifact
steps:
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/'
      artifact: 'api'
      publishLocation: 'pipeline'