trigger:
  branches:
    include:
      - infra
      - master
  paths:
    include:
      -  'api/*'
 #package API artifact
  steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/'
    artifact: 'api'
    publishLocation: 'pipeline'